version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: ai-sdr-rabbitmq
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - ai-sdr-network

volumes:
  rabbitmq_data:

networks:
  ai-sdr-network:
    driver: bridge
